--
-- PostgreSQL database dump
--

\restrict RgLC4mvvV9WbzzBa3vWzhV8T2DWUWQuoQeF4tzCecOXowjtU6m2pu51ygBDMxAi

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    action character varying(100) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    entity_id uuid NOT NULL,
    entity_type character varying(50) NOT NULL,
    ip_address inet,
    metadata jsonb,
    actor_id uuid
);


ALTER TABLE public.audit_log OWNER TO postgres;

--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invitations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invitations (
    id uuid NOT NULL,
    accepted_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(150) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    full_name character varying(150) NOT NULL,
    phone_number character varying(20),
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    token character varying(100) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    organization_id uuid NOT NULL,
    CONSTRAINT invitations_role_check CHECK (((role)::text = ANY ((ARRAY['PLATFORM_ADMIN'::character varying, 'MANUFACTURER_ADMIN'::character varying, 'MANUFACTURER_STAFF'::character varying, 'DISTRIBUTOR_ADMIN'::character varying, 'DISTRIBUTOR_STAFF'::character varying, 'DRIVER'::character varying, 'CUSTOMER'::character varying])::text[]))),
    CONSTRAINT invitations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.invitations OWNER TO postgres;

--
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    line_total numeric(12,2),
    quantity integer NOT NULL,
    stock_check_status character varying(20) NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    order_id uuid NOT NULL,
    stock_item_id uuid NOT NULL
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- Name: order_status_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_status_history (
    id uuid NOT NULL,
    changed_at timestamp(6) with time zone NOT NULL,
    from_status character varying(255),
    note text,
    to_status character varying(255) NOT NULL,
    changed_by uuid,
    order_id uuid NOT NULL,
    CONSTRAINT order_status_history_from_status_check CHECK (((from_status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'PROCESSING'::character varying, 'AWAITING_DISPATCH'::character varying, 'IN_TRANSIT'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT order_status_history_to_status_check CHECK (((to_status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'PROCESSING'::character varying, 'AWAITING_DISPATCH'::character varying, 'IN_TRANSIT'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.order_status_history OWNER TO postgres;

--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    delivery_address text,
    delivery_lat double precision,
    delivery_lng double precision,
    notes text,
    order_number character varying(50) NOT NULL,
    status character varying(30) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    customer_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'PROCESSING'::character varying, 'AWAITING_DISPATCH'::character varying, 'IN_TRANSIT'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: organizations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organizations (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(150) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT organizations_type_check CHECK (((type)::text = ANY (ARRAY[('MANUFACTURER'::character varying)::text, ('DISTRIBUTOR'::character varying)::text])))
);


ALTER TABLE public.organizations OWNER TO postgres;

--
-- Name: otp_verifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.otp_verifications (
    id uuid NOT NULL,
    attempt_count smallint NOT NULL,
    code_hash character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    destination character varying(150) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    max_attempts smallint NOT NULL,
    purpose character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    verified_at timestamp(6) with time zone,
    user_id uuid,
    CONSTRAINT otp_verifications_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['ACCOUNT_VERIFICATION'::character varying, 'LOGIN'::character varying, 'ORDER_CONFIRMATION'::character varying, 'DELIVERY_CONFIRMATION'::character varying, 'PASSWORD_RESET'::character varying])::text[]))),
    CONSTRAINT otp_verifications_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'EXPIRED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.otp_verifications OWNER TO postgres;

--
-- Name: payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments (
    id uuid NOT NULL,
    amount numeric(12,2) NOT NULL,
    callback_raw_payload jsonb,
    confirmed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    currency character varying(3) NOT NULL,
    failure_reason text,
    initiated_at timestamp(6) with time zone NOT NULL,
    method character varying(255) NOT NULL,
    mpesa_checkout_request_id character varying(100),
    mpesa_merchant_request_id character varying(100),
    mpesa_receipt_number character varying(50),
    phone_number character varying(20),
    reconciled_at timestamp(6) with time zone,
    reconciled_note text,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    order_id uuid NOT NULL,
    reconciled_by uuid,
    CONSTRAINT payments_method_check CHECK (((method)::text = ANY ((ARRAY['MPESA'::character varying, 'CASH'::character varying, 'CARD'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'FAILED'::character varying, 'REVERSED'::character varying, 'RECONCILED'::character varying])::text[])))
);


ALTER TABLE public.payments OWNER TO postgres;

--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id uuid NOT NULL,
    category character varying(80) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(500),
    name character varying(150) NOT NULL,
    organization_id uuid,
    organization_name character varying(150),
    sku character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    stock_quantity integer NOT NULL,
    unit_price numeric(12,2),
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT products_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DISCONTINUED'::character varying, 'PENDING'::character varying])::text[])))
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_tokens (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    revoked boolean NOT NULL,
    token_hash character varying(255) NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.refresh_tokens OWNER TO postgres;

--
-- Name: stock_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stock_items (
    id uuid NOT NULL,
    is_active boolean NOT NULL,
    category character varying(80),
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(150) NOT NULL,
    quantity_on_hand integer NOT NULL,
    reorder_threshold integer NOT NULL,
    sku character varying(50) NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    approval_status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL
);


ALTER TABLE public.stock_items OWNER TO postgres;

--
-- Name: stock_movements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stock_movements (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    movement_type character varying(255) NOT NULL,
    note text,
    quantity_delta integer NOT NULL,
    reference_id uuid,
    reference_type character varying(50),
    performed_by uuid,
    stock_item_id uuid NOT NULL,
    CONSTRAINT stock_movements_movement_type_check CHECK (((movement_type)::text = ANY ((ARRAY['RESTOCK_IN'::character varying, 'SALE_OUT'::character varying, 'ADJUSTMENT'::character varying, 'RETURN'::character varying, 'DAMAGE'::character varying])::text[])))
);


ALTER TABLE public.stock_movements OWNER TO postgres;

--
-- Name: trip_location_pings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trip_location_pings (
    id bigint NOT NULL,
    lat double precision NOT NULL,
    lng double precision NOT NULL,
    recorded_at timestamp(6) with time zone NOT NULL,
    trip_id uuid NOT NULL
);


ALTER TABLE public.trip_location_pings OWNER TO postgres;

--
-- Name: trip_location_pings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trip_location_pings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trip_location_pings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trip_status_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trip_status_history (
    id uuid NOT NULL,
    changed_at timestamp(6) with time zone NOT NULL,
    from_status character varying(255),
    note text,
    to_status character varying(255) NOT NULL,
    changed_by uuid,
    trip_id uuid NOT NULL,
    CONSTRAINT trip_status_history_from_status_check CHECK (((from_status)::text = ANY ((ARRAY['UNASSIGNED'::character varying, 'ASSIGNED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT trip_status_history_to_status_check CHECK (((to_status)::text = ANY ((ARRAY['UNASSIGNED'::character varying, 'ASSIGNED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.trip_status_history OWNER TO postgres;

--
-- Name: trips; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trips (
    id uuid NOT NULL,
    assigned_at timestamp(6) with time zone,
    cancelled_at timestamp(6) with time zone,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    destination_lat double precision,
    destination_lng double precision,
    estimated_eta timestamp(6) with time zone,
    origin_lat double precision,
    origin_lng double precision,
    restock_quantity integer,
    started_at timestamp(6) with time zone,
    status character varying(255) NOT NULL,
    trip_type character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    order_id uuid,
    rider_id uuid,
    stock_item_id uuid,
    CONSTRAINT trips_status_check CHECK (((status)::text = ANY ((ARRAY['UNASSIGNED'::character varying, 'ASSIGNED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT trips_trip_type_check CHECK (((trip_type)::text = ANY ((ARRAY['RESTOCK'::character varying, 'DELIVERY'::character varying])::text[])))
);


ALTER TABLE public.trips OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(150),
    is_email_verified boolean NOT NULL,
    full_name character varying(150) NOT NULL,
    phone_number character varying(20) NOT NULL,
    is_phone_verified boolean NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    password_hash character varying(255) NOT NULL,
    organization_id uuid,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['PLATFORM_ADMIN'::character varying, 'MANUFACTURER_ADMIN'::character varying, 'MANUFACTURER_STAFF'::character varying, 'DISTRIBUTOR_ADMIN'::character varying, 'DISTRIBUTOR_STAFF'::character varying, 'DRIVER'::character varying, 'CUSTOMER'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'DEACTIVATED'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Data for Name: audit_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.audit_log (id, action, created_at, entity_id, entity_type, ip_address, metadata, actor_id) FROM stdin;
\.


--
-- Data for Name: invitations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invitations (id, accepted_at, created_at, email, expires_at, full_name, phone_number, role, status, token, updated_at, organization_id) FROM stdin;
\.


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_items (id, created_at, line_total, quantity, stock_check_status, unit_price, order_id, stock_item_id) FROM stdin;
\.


--
-- Data for Name: order_status_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_status_history (id, changed_at, from_status, note, to_status, changed_by, order_id) FROM stdin;
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, created_at, delivery_address, delivery_lat, delivery_lng, notes, order_number, status, total_amount, updated_at, customer_id, organization_id) FROM stdin;
\.


--
-- Data for Name: organizations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.organizations (id, created_at, name, type, updated_at) FROM stdin;
5d9eb6c9-62c2-4a1d-840a-6e21465fa2f6	2026-09-30 14:31:49.938178+03	Test Distribution Company	DISTRIBUTOR	2026-09-30 14:31:49.938178+03
930ae6cd-b529-4ed6-b98d-872b505b56be	2026-10-01 10:36:04.937185+03	Moses Paints	MANUFACTURER	2026-10-01 10:36:04.937185+03
d4255cc9-887f-44c9-a92e-cab54167fddc	2026-10-01 13:10:50.222792+03	Doe Mabati	DISTRIBUTOR	2026-10-01 13:10:50.228378+03
eb3a5275-71cc-4e99-9469-4c95048dd1a7	2026-10-02 12:45:48.15694+03	Benjo & Sons Hardware	DISTRIBUTOR	2026-10-02 12:45:48.15694+03
329999ae-5266-4856-b874-4e4c02984bc5	2026-10-05 09:39:44.684115+03	UPS	DISTRIBUTOR	2026-10-05 09:39:44.684115+03
3ed29966-fa82-4c57-8bc6-215876032676	2026-10-05 11:09:12.801957+03	Nails Limited	MANUFACTURER	2026-10-05 11:09:12.801957+03
\.


--
-- Data for Name: otp_verifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.otp_verifications (id, attempt_count, code_hash, created_at, destination, expires_at, max_attempts, purpose, status, verified_at, user_id) FROM stdin;
4e3a6421-dd44-4832-9c27-2173e55a72ad	0	$2a$12$uv3wLqS9p5LUjlYpEpKni.qEXNu/YV4urQaF5AS2rNxd392LTAdtO	2026-09-30 14:31:49.946857+03	+254712345678	2026-09-30 14:36:49.607869+03	5	ACCOUNT_VERIFICATION	EXPIRED	\N	d652dc24-735f-4ce6-a0d7-e418e0134106
5b47362a-30f0-43d6-95d6-0215b77ba52f	0	$2a$12$pfQthFnHJipc.E8upCTtYu/Z7WD6unl3owC0ZxpxYMC1cQZh4/VfO	2026-09-30 14:42:10.702785+03	+254712345678	2026-09-30 14:47:10.374193+03	5	ACCOUNT_VERIFICATION	VERIFIED	2026-09-30 14:43:42.896886+03	d652dc24-735f-4ce6-a0d7-e418e0134106
c5a2ee10-0776-4147-816d-61c86f51d7f6	0	$2a$12$00.mUxX3/fImwMTytfdHQONfkx0Y8H/Biz9E/Z2xtPtj1KJQdp3Jm	2026-10-01 10:36:05.017095+03	+2547890384754	2026-10-01 10:41:03.599303+03	5	ACCOUNT_VERIFICATION	PENDING	\N	5fbe0b52-59ee-4cc7-8cf2-9e7124c61476
07322912-77a6-49e1-8bcc-9a532102cbfe	0	$2a$12$N2pxYGJSfBsjiIjbC3jUgOrMBvpKsTRA44mc/YHnr8XOIVyZXTAJm	2026-10-01 13:10:50.248286+03	+254743017982	2026-10-01 13:15:49.593566+03	5	ACCOUNT_VERIFICATION	VERIFIED	2026-10-01 13:12:41.206382+03	4a2929c0-3ac4-4a98-839a-dd888e8307c8
5e590373-1f85-4dc8-9286-e79fd87e6ffd	0	$2a$12$QKD3OLxyghLRASB6DoUrjOP2eVuDHm8miN9VdzDZR3597CRYu5oMe	2026-10-05 09:39:44.707152+03	+254768950493	2026-10-05 09:44:43.464118+03	5	ACCOUNT_VERIFICATION	PENDING	\N	c6a9f35c-3afe-4bd6-915a-a9a5e355f072
f7ee089d-a89f-4afa-bdf2-bb06cd70aa28	0	$2a$12$h8Q1CMItlFr8oq8eYzx1CuL.2kar6IRMPDVuUktyp2OfPRIFcIEdy	2026-10-05 11:09:12.845671+03	+254743782015	2026-10-05 11:14:11.618245+03	5	ACCOUNT_VERIFICATION	VERIFIED	2026-10-05 11:09:41.732734+03	0748ca63-305f-46be-add8-9da1509df041
\.


--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payments (id, amount, callback_raw_payload, confirmed_at, created_at, currency, failure_reason, initiated_at, method, mpesa_checkout_request_id, mpesa_merchant_request_id, mpesa_receipt_number, phone_number, reconciled_at, reconciled_note, status, updated_at, order_id, reconciled_by) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, category, created_at, description, name, organization_id, organization_name, sku, status, stock_quantity, unit_price, updated_at) FROM stdin;
\.


--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.refresh_tokens (id, created_at, expires_at, revoked, token_hash, user_id) FROM stdin;
351569fd-142d-408d-a6d8-98267e7864ab	2026-09-30 14:43:43.54428+03	2026-10-07 14:43:43.544281+03	f	a88a14f2b522a6c45692451f791d014af755fcca7b73154e975e02440216be2b	d652dc24-735f-4ce6-a0d7-e418e0134106
293fefcb-c850-45cb-8115-183246bda6dc	2026-09-30 14:49:31.478574+03	2026-10-07 14:49:31.471525+03	f	d588322461aa7b3f1c5016bfeeab753ebff8138669b7491ced1bcbae09a3ef8c	d652dc24-735f-4ce6-a0d7-e418e0134106
23d36419-b117-4311-8496-b14591319396	2026-09-30 15:44:58.296933+03	2026-10-07 15:44:58.26509+03	f	0c7e60f02dcdb4c59336b07142e31cda423bce4d9695edd819592f96b450d0fa	d652dc24-735f-4ce6-a0d7-e418e0134106
a7e56fd5-f2f7-4860-8eda-93b861481a1e	2026-10-01 12:25:20.520728+03	2026-10-08 12:25:20.400177+03	f	f06470e6a61f2c403fc1def9f1cb50c0a86c14c34bd5cbdd3569a1c85f7b6aeb	751557cf-9824-4ea1-a0ed-538937e2aa2e
9123a29b-7a37-4596-9e78-0c6f7dea8dec	2026-10-01 13:12:41.894871+03	2026-10-08 13:12:41.890834+03	f	cf48c02d273816ffe3db7e058f1c56bd77070eaf799ab76e9b4bed19abdc3ce2	4a2929c0-3ac4-4a98-839a-dd888e8307c8
0ff8e4be-2654-4619-b206-02a5ed71c49e	2026-10-01 13:13:09.806162+03	2026-10-08 13:13:09.806163+03	f	0d27dbfb93fe79785dd7bf8eafd79d1eb6f16e810e9abaf2dd6a52bea6133f5f	4a2929c0-3ac4-4a98-839a-dd888e8307c8
83d8903f-6202-452c-8e06-b0c06f9a3921	2026-10-02 11:12:35.51347+03	2026-10-09 11:12:35.407604+03	t	e5dcf854fa0f48c5e0a832719bfbacf4323d182ade27cab33802c3113fc971c7	751557cf-9824-4ea1-a0ed-538937e2aa2e
1cb9ba56-1fe9-4115-9cdc-1d2a2af87149	2026-10-02 12:28:24.918871+03	2026-10-09 12:28:24.866856+03	t	4b24da7c67ed01ba38162e43cd467cce8bb2d04149062c5bb56b0aac81875db2	751557cf-9824-4ea1-a0ed-538937e2aa2e
9efd923f-7a34-4e3a-8b66-c6a65993bd73	2026-10-02 12:42:52.670917+03	2026-10-09 12:42:52.669919+03	t	ea4ad81d1631b235c0026d94f190a667436b43336dcd9d61f681cac4b93a0dab	751557cf-9824-4ea1-a0ed-538937e2aa2e
a57e659e-dd86-415b-9ca8-194a754504a6	2026-10-02 15:35:34.683931+03	2026-10-09 15:35:34.635763+03	t	615beb56e450d7ea4571a7ee7c7aba2082e17baa60ebda6dabeb163f1613dd8d	751557cf-9824-4ea1-a0ed-538937e2aa2e
34e56d31-221f-4077-9e6a-ef964103e46b	2026-10-02 15:47:18.042623+03	2026-10-09 15:47:17.996569+03	t	c43c1f8742097af8d1fd0f6f1ade210e22e064762c563c4888332988c096b4fd	751557cf-9824-4ea1-a0ed-538937e2aa2e
405003ed-b852-4a42-bee4-70fe3d0b55cb	2026-10-05 09:26:50.311644+03	2026-10-12 09:26:50.251906+03	t	e44cca50208540bde99b2bb917d4ad39d56f433623eca198298094e8b8295e77	751557cf-9824-4ea1-a0ed-538937e2aa2e
dabe5581-9367-4557-9162-26724f661b81	2026-10-05 10:00:01.599877+03	2026-10-12 10:00:01.499507+03	t	4701f1a48c2b8607d2a4d33d073cfdf316507e63cf67fb19c1a0c0ac08061e39	751557cf-9824-4ea1-a0ed-538937e2aa2e
cc4dea20-15d2-4c15-8082-d5039f1b9631	2026-10-05 11:00:17.11524+03	2026-10-12 11:00:17.113116+03	t	420a2f5745c388d871784e9ad7580a8564ca42f19ef09157c280033f6ef70b94	751557cf-9824-4ea1-a0ed-538937e2aa2e
5770cc9c-db90-4b11-9290-9a2388298ad6	2026-10-05 11:09:42.899792+03	2026-10-12 11:09:42.896548+03	f	37c9ce15f2bf80ab2699eb2a9a341c348fe67dd1396bc7c43a83442c05a6f291	0748ca63-305f-46be-add8-9da1509df041
c80ae458-06cd-4777-bcf9-5292905e117f	2026-10-05 11:10:03.273432+03	2026-10-12 11:10:03.271342+03	f	6649f14426e0ecf5b74c5ae51b5e89beea4d2c54e8ed2247d07da58442e99194	0748ca63-305f-46be-add8-9da1509df041
9f01108f-4bf5-4f22-80a2-82efdf2ac21b	2026-10-05 11:14:19.015535+03	2026-10-12 11:14:19.010522+03	f	f3fa90b508e9dd1c666e2908fb5a02f761f016a71e7687ef8964e2bf9e749e47	0748ca63-305f-46be-add8-9da1509df041
467ac88f-7e4c-4659-96ee-79d9c9d2f0a3	2026-10-05 11:14:46.22046+03	2026-10-12 11:14:46.21844+03	t	0ebff8dd1896e407ef673e437aa4494fe291e58bed492a938c6b166373bed72a	751557cf-9824-4ea1-a0ed-538937e2aa2e
e3449a3b-3d11-4edf-8396-eb22c7f53796	2026-10-05 11:50:17.513559+03	2026-10-12 11:50:17.503486+03	t	0f354693c0c38b7b9f15757bd58cf5a6d9bdd2f7fae4acd427adf0dad6f6225d	751557cf-9824-4ea1-a0ed-538937e2aa2e
0a9a153f-06e6-4846-8405-f736621a9d09	2026-10-05 12:13:55.020489+03	2026-10-12 12:13:55.015903+03	f	7570c395ae0035cc5d93ba338fc701f790da795089cf284a67e9081dfba1df6d	751557cf-9824-4ea1-a0ed-538937e2aa2e
\.


--
-- Data for Name: stock_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stock_items (id, is_active, category, created_at, name, quantity_on_hand, reorder_threshold, sku, unit_price, updated_at, approval_status) FROM stdin;
a81468be-6c92-4c57-a16d-7d86a8629417	t	Construction	2026-10-02 15:47:49.267953+03	Mabati	0	0	PRD-001	500.00	2026-10-02 15:47:49.267953+03	PENDING
a1fb6e2f-ab15-4949-8bb3-9266aec863d6	t	Construction	2026-10-05 11:15:32.215409+03	Nails	0	0	PRD-002	250.00	2026-10-05 11:15:32.215409+03	PENDING
\.


--
-- Data for Name: stock_movements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stock_movements (id, created_at, movement_type, note, quantity_delta, reference_id, reference_type, performed_by, stock_item_id) FROM stdin;
\.


--
-- Data for Name: trip_location_pings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trip_location_pings (id, lat, lng, recorded_at, trip_id) FROM stdin;
\.


--
-- Data for Name: trip_status_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trip_status_history (id, changed_at, from_status, note, to_status, changed_by, trip_id) FROM stdin;
\.


--
-- Data for Name: trips; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trips (id, assigned_at, cancelled_at, completed_at, created_at, destination_lat, destination_lng, estimated_eta, origin_lat, origin_lng, restock_quantity, started_at, status, trip_type, updated_at, order_id, rider_id, stock_item_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, created_at, email, is_email_verified, full_name, phone_number, is_phone_verified, role, status, updated_at, password_hash, organization_id) FROM stdin;
d652dc24-735f-4ce6-a0d7-e418e0134106	2026-09-30 14:31:49.938178+03	testadmin@example.com	f	Test Distributor Admin	+254712345678	t	DISTRIBUTOR_ADMIN	ACTIVE	2026-09-30 14:43:43.552182+03	$2a$12$6dPm7Rcvn0K6Tk3HD9700uC4/f5JK6NNW5lGlTmFAY1NikvBGmPr2	5d9eb6c9-62c2-4a1d-840a-6e21465fa2f6
5fbe0b52-59ee-4cc7-8cf2-9e7124c61476	2026-10-01 10:36:05.001133+03	jumamoses@yahoo.com	f	Moses Juma	+2547890384754	f	MANUFACTURER_ADMIN	ACTIVE	2026-10-01 10:36:05.001133+03	$2a$12$VqWZCvZdQf2i4Opc8t8m.ebBSYTOh9hpdPc8yK2SpKtQJf.Clmw96	930ae6cd-b529-4ed6-b98d-872b505b56be
751557cf-9824-4ea1-a0ed-538937e2aa2e	2026-10-01 12:04:08.001874+03	michellemakimei@gmail.com	t	Michelle Makimei	0740383242	t	PLATFORM_ADMIN	ACTIVE	2026-10-01 12:04:08.001874+03	$2a$12$MdvLtjYVCTxoE3wnSa85PO7Ht/xjeOZPTGFn8QOeLuZ7pQ6yimOOG	\N
4a2929c0-3ac4-4a98-839a-dd888e8307c8	2026-10-01 13:10:50.238465+03	doejoe@gmail.com	f	Joseph Doe	+254743017982	t	DISTRIBUTOR_ADMIN	ACTIVE	2026-10-01 13:12:41.902831+03	$2a$12$ccppNvxTZtfL/Yt2AKF3qekYQjK43ijG/Pf8M8k1TjQLWUARfv0D.	d4255cc9-887f-44c9-a92e-cab54167fddc
c6a9f35c-3afe-4bd6-915a-a9a5e355f072	2026-10-05 09:39:44.693652+03	ups@gmail.com	f	Amy Mark	+254768950493	f	DISTRIBUTOR_ADMIN	ACTIVE	2026-10-05 09:39:44.693652+03	$2a$12$mM2/BCypt6nj7l9x82W6V.tmWN5w1nWe/SHBVtcI8rlQ6Kf1XDw.q	329999ae-5266-4856-b874-4e4c02984bc5
0748ca63-305f-46be-add8-9da1509df041	2026-10-05 11:09:12.819934+03	kernails@yahoo.com	f	Jace Michaels	+254743782015	t	MANUFACTURER_ADMIN	ACTIVE	2026-10-05 11:09:42.914038+03	$2a$12$P8dmd2VlfxvD0gKInN9c8eaLojGIlF6xAkXuMYhgdeLaB0zAJD3k2	3ed29966-fa82-4c57-8bc6-215876032676
\.


--
-- Name: audit_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.audit_log_id_seq', 1, false);


--
-- Name: trip_location_pings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trip_location_pings_id_seq', 1, false);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: invitations invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: order_status_history order_status_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_status_history
    ADD CONSTRAINT order_status_history_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: organizations organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);


--
-- Name: otp_verifications otp_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_verifications
    ADD CONSTRAINT otp_verifications_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: stock_items stock_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock_items
    ADD CONSTRAINT stock_items_pkey PRIMARY KEY (id);


--
-- Name: stock_movements stock_movements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock_movements
    ADD CONSTRAINT stock_movements_pkey PRIMARY KEY (id);


--
-- Name: trip_location_pings trip_location_pings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trip_location_pings
    ADD CONSTRAINT trip_location_pings_pkey PRIMARY KEY (id);


--
-- Name: trip_status_history trip_status_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trip_status_history
    ADD CONSTRAINT trip_status_history_pkey PRIMARY KEY (id);


--
-- Name: trips trips_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users uk9q63snka3mdh91as4io72espi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk9q63snka3mdh91as4io72espi UNIQUE (phone_number);


--
-- Name: products ukfhmd06dsmj6k0n90swsh8ie9g; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT ukfhmd06dsmj6k0n90swsh8ie9g UNIQUE (sku);


--
-- Name: stock_items ukiu19dji9fip92nhy9a14ysuy9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock_items
    ADD CONSTRAINT ukiu19dji9fip92nhy9a14ysuy9 UNIQUE (sku);


--
-- Name: orders uknthkiu7pgmnqnu86i2jyoe2v7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uknthkiu7pgmnqnu86i2jyoe2v7 UNIQUE (order_number);


--
-- Name: refresh_tokens uko2mlirhldriil2y7krapq4frt; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uko2mlirhldriil2y7krapq4frt UNIQUE (token_hash);


--
-- Name: payments uksrl1m8wlbd1atlb2a9bv6svbi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uksrl1m8wlbd1atlb2a9bv6svbi UNIQUE (mpesa_checkout_request_id);


--
-- Name: invitations ukt4i6esv44p6yi7cxq277vlo3i; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT ukt4i6esv44p6yi7cxq277vlo3i UNIQUE (token);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_order_customer; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_customer ON public.orders USING btree (customer_id);


--
-- Name: idx_order_org; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_org ON public.orders USING btree (organization_id);


--
-- Name: idx_order_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_status ON public.orders USING btree (status);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: trips fk5c1ek6pnbbx9g32gl399vxvm5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fk5c1ek6pnbbx9g32gl399vxvm5 FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: payments fk81gagumt0r8y3rmudcgpbk42l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: order_items fk99ufc1c4rsx7cts9twmpftxo5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk99ufc1c4rsx7cts9twmpftxo5 FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: trip_status_history fkcxc5kh1g3k2iycex4q1esxf02; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trip_status_history
    ADD CONSTRAINT fkcxc5kh1g3k2iycex4q1esxf02 FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: trips fkg2ydq5cg1yq0jo1e38upculpm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fkg2ydq5cg1yq0jo1e38upculpm FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id);


--
-- Name: payments fkh4ugrvl0ngw69o3dvd3m5m0eq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkh4ugrvl0ngw69o3dvd3m5m0eq FOREIGN KEY (reconciled_by) REFERENCES public.users(id);


--
-- Name: trip_status_history fkiprwdpn4i2sdmxv5a0o2hb197; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trip_status_history
    ADD CONSTRAINT fkiprwdpn4i2sdmxv5a0o2hb197 FOREIGN KEY (changed_by) REFERENCES public.users(id);


--
-- Name: order_status_history fkj7bba43h8j0n4evd2wvudvpjc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_status_history
    ADD CONSTRAINT fkj7bba43h8j0n4evd2wvudvpjc FOREIGN KEY (changed_by) REFERENCES public.users(id);


--
-- Name: stock_movements fklaob67k5ekyx7qnir6ekb99jy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock_movements
    ADD CONSTRAINT fklaob67k5ekyx7qnir6ekb99jy FOREIGN KEY (performed_by) REFERENCES public.users(id);


--
-- Name: orders fkmnqry320pwe9sb3kvil9r28f9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkmnqry320pwe9sb3kvil9r28f9 FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: order_status_history fknmcbg3mmbt8wfva97ra40nmp3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_status_history
    ADD CONSTRAINT fknmcbg3mmbt8wfva97ra40nmp3 FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: stock_movements fknpt24ujdtowfdohxkvop7mewp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock_movements
    ADD CONSTRAINT fknpt24ujdtowfdohxkvop7mewp FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id);


--
-- Name: audit_log fkp0xyrkkoeraheio5qt1iihlo1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT fkp0xyrkkoeraheio5qt1iihlo1 FOREIGN KEY (actor_id) REFERENCES public.users(id);


--
-- Name: trips fkp458j3lp2131ja1myueksc8a9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fkp458j3lp2131ja1myueksc8a9 FOREIGN KEY (rider_id) REFERENCES public.users(id);


--
-- Name: trip_location_pings fkp8fie2oxdygd544omaaixnfom; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trip_location_pings
    ADD CONSTRAINT fkp8fie2oxdygd544omaaixnfom FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: invitations fkq0jssk151g1kt9cx4vnomojc9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT fkq0jssk151g1kt9cx4vnomojc9 FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: users fkqpugllwvyv37klq7ft9m8aqxk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkqpugllwvyv37klq7ft9m8aqxk FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: orders fksjfs85qf6vmcurlx43cnc16gy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fksjfs85qf6vmcurlx43cnc16gy FOREIGN KEY (customer_id) REFERENCES public.users(id);


--
-- Name: otp_verifications fkssn2wgmijxelm0u26ti271lcf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_verifications
    ADD CONSTRAINT fkssn2wgmijxelm0u26ti271lcf FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict RgLC4mvvV9WbzzBa3vWzhV8T2DWUWQuoQeF4tzCecOXowjtU6m2pu51ygBDMxAi

